# Use a lightweight base image with JDK 17
FROM eclipse-temurin:17-jdk-jammy

# Set the working directory inside the container
WORKDIR /app

# Copy the application's executable JAR file from your Maven 'target' directory
# The `*.jar` is a wildcard to match the full JAR filename generated by Maven
COPY target/deutsche-springboot-demo-*.jar app.jar

# Expose the application's port (as configured in application.properties)
EXPOSE 8090

# Define the command to run the application when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]