name: Spring Boot CI

# This workflow runs on every push and pull request to the 'main' branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A job is a set of steps that run on a runner (a virtual machine)
jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu version for the runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to get your code from the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Action to install a specific Java version
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # Caches Maven dependencies for faster builds

      - name: Build with Maven
        run: mvn -B package --file pom.xml # Command to build your project using Maven

      - name: Verify Build Artifact
        run: ls -l target/*.jar # Lists the contents of the target directory to confirm the JAR was created